spring.application.name=Order_management

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/orderManagement}
spring.datasource.username=root
spring.datasource.password=Rishabh9161@

spring.jpa.hibernate.ddl-auto=update
#hibernate automatically: creates table,update schema
#create,update,validate,create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#Hibernate generates MySQL-compatible SQL.
spring.jpa.show-sql=true
#show sql queries in console